-- Ti Kloud: application schema
-- Database role "tikloud" (the Postgres chart user) owns these tables. There is
-- no per-row database authorization: row access is enforced by the app from the
-- Keycloak session (profiles.id is the Keycloak "sub" claim).

create table if not exists profiles (
  id text primary key,
  email text,
  display_name text,
  created_at timestamptz not null default now()
);

create table if not exists waitlist (
  id bigint generated by default as identity primary key,
  email text not null unique,
  created_at timestamptz not null default now()
);
