{{- range $service := .Values.services }}
{{- if and $service.enabled $service.autoscaling.enabled }}
{{- $ctx := dict "root" $ "service" $service }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "tikloud.serviceFullname" $ctx }}
  labels:
    {{- include "tikloud.serviceLabels" $ctx | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "tikloud.serviceFullname" $ctx }}
  minReplicas: {{ $service.autoscaling.minReplicas | default 1 }}
  maxReplicas: {{ $service.autoscaling.maxReplicas | default 10 }}
  metrics:
    {{- if $service.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ $service.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if $service.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ $service.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
---
{{- end }}
{{- end }}
