{{- if .Values.keycloak.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "tikloud.keycloakFullname" . }}
  labels:
    {{- include "tikloud.keycloakLabels" . | nindent 4 }}
spec:
  type: {{ .Values.keycloak.service.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.keycloak.service.port | default 8080 }}
      targetPort: {{ .Values.keycloak.httpPort | default 8080 }}
      protocol: TCP
      name: http
  selector:
    {{- include "tikloud.keycloakSelectorLabels" . | nindent 4 }}
{{- end }}
