{{- if .Values.keycloak.enabled }}
{{- if not .Values.keycloak.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tikloud.keycloakSecretName" . }}
  labels:
    {{- include "tikloud.keycloakLabels" . | nindent 4 }}
type: Opaque
data:
  {{- $secretName := include "tikloud.keycloakSecretName" . }}
  {{- $existing := (lookup "v1" "Secret" .Release.Namespace $secretName) }}
  admin-password: {{ if and $existing (index $existing.data "admin-password") }}{{ index $existing.data "admin-password" }}{{ else }}{{ randAlphaNum 40 | b64enc | quote }}{{ end }}
  db-password: {{ if and $existing (index $existing.data "db-password") }}{{ index $existing.data "db-password" }}{{ else }}{{ randAlphaNum 40 | b64enc | quote }}{{ end }}
{{- end }}
{{- end }}
