name: Expo

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v5.0.0

      - name: Setup Node.js
        uses: actions/setup-node@v5.0.0
        with:
          cache: node
          node-version: 24.7.0

      - name: Install dependencies
        run: npm install

      - name: Run lint
        run: npm run lint

  export:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v5.0.0

      - name: Setup Node.js
        uses: actions/setup-node@v5.0.0
        with:
          cache: node
          node-version: 24.7.0

      - name: Install dependencies
        run: npm install

      - name: Export the project
        run: npm run export
